---
- hosts: dev
  tasks:
   - name: Download Java
     command: sudo yum install java-1.8.0-openjdk -y

   - name: Unpack archive
     command: sudo yum install java-1.8.0-openjdk-devel -y

   - name: check java version
     command: java -version

   - name: Create Folder
     file:
      path: /home/ec2-user/tomcat_new
      state: directory
      mode: 0755
      owner: ec2-user
      group: ec2-user

   - name: Download Tomcat
     get_url: url=http://mirrors.koehn.com/apache/tomcat/tomcat-8/v8.5.46/bin/apache-tomcat-8.5.46.tar.gz dest=/home/ec2-user/tomcat_new


   - name: Extract archive
     #unarchive: src=/home/ec2-user/apache-tomcat-8.5.46.tar.gz dest=/home/ec2-user/ remote_src=yes 
     command: tar -xvzf /home/ec2-user/tomcat_new/apache-tomcat-8.5.46.tar.gz

   - name: deploying the application
     copy: src=/var/lib/jenkins/workspace/Demo/target/CounterWebApp.war dest=/home/ec2-user/tomcat_new/apache-tomcat-8.5.46/webapps/
  
   
   - name: start apache-tomcat-8.5.46/
     command: sh /home/ec2-user/tomcat_new/apache-tomcat-8.5.46/bin/startup.sh
